services:
  #==============================================================================
  # BASE SERVICE
  #==============================================================================
  # Minimal base image without ROS packages - used for building other images
  base:
    build:
      context: .
      dockerfile: dockerfiles/base.dockerfile
    image: base:latest
    pull_policy: build
    env_file:
      - .env

  #==============================================================================
  # BASE SERVICE TEMPLATES
  #==============================================================================
  # These are abstract base services that define common configurations
  # They are extended by actual service definitions below

  # Common base: shared by all containers
  x-common-base:
    privileged: true
    network_mode: host # Required for ROS communication
    env_file:
      - .env
    stdin_open: true
    tty: true
    profiles: ["abstract"] # Optional: avoids appearing in `docker compose ps`

  # Standard base - includes basic ROS setup and common dependencies
  x-base:
    extends: x-common-base

  # Standard package base - for ROS packages without special requirements
  x-package-base:
    extends: x-common-base
    depends_on:
      - base
    build:
      context: .
      dockerfile: dockerfiles/package.dockerfile
      args:
        - PIP_BREAK_SYSTEM_PACKAGES=${PIP_BREAK_SYSTEM_PACKAGES}
    volumes:
      - ./packages/src:/home/ubuntu/workspace/packages/src:cached

  # Physical car base - includes device access for hardware communication
  x-physical-base:
    extends: x-common-base
    depends_on:
      - base
    build:
      context: .
      dockerfile: dockerfiles/package.dockerfile
      args:
        - PIP_BREAK_SYSTEM_PACKAGES=${PIP_BREAK_SYSTEM_PACKAGES}
    volumes:
      - /dev:/dev # Device access for hardware
      - ./packages/src:/home/ubuntu/workspace/packages/src:cached

  # GUI base - includes X11 forwarding for graphical applications
  x-gui-base:
    extends: x-common-base
    depends_on:
      - base
    build:
      context: .
      dockerfile: dockerfiles/package.dockerfile
      args:
        - PIP_BREAK_SYSTEM_PACKAGES=${PIP_BREAK_SYSTEM_PACKAGES}
    volumes:
      - ./packages/src:/home/ubuntu/workspace/packages/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 socket for GUI
      - ${XDG_RUNTIME_DIR}:/tmp/runtime-ubuntu:rw
    environment:
      - DISPLAY=${DISPLAY} # Forward display for GUI applications
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
      - QT_X11_NO_MITSHM=1 # X11 optimization flags

  # Development base - full workspace mount for development workflow
  x-dev-base:
    extends: x-common-base
    depends_on:
      - base
    build:
      context: .
      dockerfile: dockerfiles/development.dockerfile
      args:
        - PIP_BREAK_SYSTEM_PACKAGES=${PIP_BREAK_SYSTEM_PACKAGES}
    user: "ubuntu"
    volumes:
      - /dev:/dev # Device access for hardware
      - .:/home/ubuntu/workspace:cached # Full workspace for development
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 socket for GUI
      - ${XDG_RUNTIME_DIR}:/tmp/runtime-ubuntu:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
      - QT_X11_NO_MITSHM=1

  #==============================================================================
  # NETWORK SERVICES
  #==============================================================================
  # Services for network communication and data exchange

  # Zenohd - distributed data exchange service
  zenohd:
    extends: x-package-base
    image: zenohd:latest
    pull_policy: build
    container_name: zenohd
    command: ["ros2", "run", "rmw_zenoh_cpp", "rmw_zenohd"]
    profiles: ["zenohd", "sim_scenario"]

  #==============================================================================
  # PHYSICAL CAR SERVICES
  #==============================================================================
  # Services for running on the physical F1TENTH car

  # Main physical car service - launches all car-related nodes
  # physical_car:
  #   extends: x-physical-base
  #   build:
  #     args:
  #       - PACKAGE_NAMES=${PHYSICAL_CAR_PACKAGES}
  #   image: physical_car:latest
  #   container_name: physical_car
  #   env_file:
  #     - .env
  #   command: ["ros2", "launch", "physical_car", "physical_car.launch.py"]
  #   profiles: ["real"]

  #==============================================================================
  # CONTROL & TELEOPERATION SERVICES
  #==============================================================================
  # Services for manual control and command multiplexing

  # Keyboard teleoperation - manual control via keyboard
  teleop:
    extends: x-gui-base
    build:
      args:
        - PACKAGE_NAMES=${TELEOP_PACKAGES}
    image: teleop:latest
    pull_policy: build
    container_name: teleop
    command:
      [
        "/bin/bash",
        "-c",
        "source /home/ubuntu/workspace/packages/install/setup.bash && cd packages && source install/setup.bash && ros2 run auna_teleoperation keyboard_teleop_hold --ros-args --params-file src/auna_teleoperation/config/key_teleop.yaml -p twist_stamped_enabled:=true",
      ]

  #==============================================================================
  # SIMULATION SERVICES
  #==============================================================================
  # Services for running in simulation environment

  gazebo:
    extends: x-gui-base
    build:
      args:
        - PACKAGE_NAMES=${GAZEBO_PACKAGES}
    image: gazebo:latest
    pull_policy: build
    container_name: gazebo
    command:
      ["/bin/bash", "-c", "ros2 launch auna_gazebo gazebo_world.launch.py"]
    profiles: ["sim", "sim_scenario"]

  spawn_robot:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${GAZEBO_PACKAGES}
    image: spawn_robot:latest
    pull_policy: build
    container_name: spawn_robot
    command: ["ros2", "launch", "auna_gazebo", "spawn_robot.launch.py"]

  spawn_robot_robot1:
    extends: spawn_robot
    container_name: spawn_robot_robot1
    command:
      [
        "ros2",
        "launch",
        "auna_gazebo",
        "spawn_robot.launch.py",
        "robot_index:=1",
      ]
    profiles: ["sim_robot1", "sim_scenario"]

  spawn_robot_robot2:
    extends: spawn_robot
    container_name: spawn_robot_robot2
    command:
      [
        "ros2",
        "launch",
        "auna_gazebo",
        "spawn_robot.launch.py",
        "robot_index:=2",
      ]
    profiles: ["sim_robot2", "sim_scenario"]

  spawn_robot_robot3:
    extends: spawn_robot
    container_name: spawn_robot_robot3
    command:
      [
        "ros2",
        "launch",
        "auna_gazebo",
        "spawn_robot.launch.py",
        "robot_index:=3",
      ]
    profiles: ["sim_robot3", "sim_scenario"]

  #==============================================================================
  # TF SERVICES
  #==============================================================================
  # Services for publishing tf and pose data

  global_tf:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${TF_PACKAGES}
    image: global_tf:latest
    pull_policy: build
    container_name: global_tf
    command: ["ros2", "launch", "auna_tf", "global_tf.launch.py"]
    profiles: ["sim", "sim_scenario"]

  localization_pose:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${TF_PACKAGES}
    image: localization_pose:latest
    pull_policy: build
    container_name: localization_pose
    command:
      ["ros2", "launch", "auna_tf", "localization_pose_publisher.launch.py"]

  localization_pose_robot1:
    extends: localization_pose
    container_name: localization_pose_robot1
    command:
      [
        "ros2",
        "launch",
        "auna_tf",
        "localization_pose_publisher.launch.py",
        "robot_index:=1",
      ]
    profiles: ["sim_robot1", "physical_robot1", "sim_scenario"]

  localization_pose_robot2:
    extends: localization_pose
    container_name: localization_pose_robot2
    command:
      [
        "ros2",
        "launch",
        "auna_tf",
        "localization_pose_publisher.launch.py",
        "robot_index:=2",
      ]
    profiles: ["sim_robot2", "physical_robot2", "sim_scenario"]

  localization_pose_robot3:
    extends: localization_pose
    container_name: localization_pose_robot3
    command:
      [
        "ros2",
        "launch",
        "auna_tf",
        "localization_pose_publisher.launch.py",
        "robot_index:=3",
      ]
    profiles: ["sim_robot3", "physical_robot3", "sim_scenario"]

  #==============================================================================
  # GROUND TRUTH SERVICES
  #==============================================================================
  # Services for publishing ground truth data

  ground_truth:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${GROUND_TRUTH_PACKAGES}
    image: ground_truth:latest
    pull_policy: build
    container_name: ground_truth
    command: ["ros2", "launch", "auna_ground_truth", "ground_truth.launch.py"]

  ground_truth_robot1:
    extends: ground_truth
    container_name: ground_truth_robot1
    command:
      [
        "ros2",
        "launch",
        "auna_ground_truth",
        "ground_truth.launch.py",
        "robot_index:=1",
      ]
    profiles: ["sim_robot1", "sim_scenario"]

  ground_truth_robot2:
    extends: ground_truth
    container_name: ground_truth_robot2
    command:
      [
        "ros2",
        "launch",
        "auna_ground_truth",
        "ground_truth.launch.py",
        "robot_index:=2",
      ]
    profiles: ["sim_robot2", "sim_scenario"]

  ground_truth_robot3:
    extends: ground_truth
    container_name: ground_truth_robot3
    command:
      [
        "ros2",
        "launch",
        "auna_ground_truth",
        "ground_truth.launch.py",
        "robot_index:=3",
      ]
    profiles: ["sim_robot3", "sim_scenario"]

  #==============================================================================
  # CMD MULTIPLEXER SERVICES
  #==============================================================================
  # Services for multiplexing command sources

  cmd_multiplexer:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${CONTROL_PANEL_PACKAGES}
    image: cmd_multiplexer:latest
    pull_policy: build
    container_name: cmd_multiplexer
    command: ["ros2", "launch", "auna_control", "cmd_vel_multiplexer.launch.py"]

  cmd_multiplexer_robot1:
    extends: cmd_multiplexer
    container_name: cmd_multiplexer_robot1
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "cmd_multiplexer.launch.py",
        "robot_index:=1",
      ]
    profiles: ["sim_robot1", "physical_robot1", "sim_scenario"]

  cmd_multiplexer_robot2:
    extends: cmd_multiplexer
    container_name: cmd_multiplexer_robot2
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "cmd_multiplexer.launch.py",
        "robot_index:=2",
      ]
    profiles: ["sim_robot2", "physical_robot2", "sim_scenario"]

  cmd_multiplexer_robot3:
    extends: cmd_multiplexer
    container_name: cmd_multiplexer_robot3
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "cmd_multiplexer.launch.py",
        "robot_index:=3",
      ]
    profiles: ["sim_robot3", "physical_robot3", "sim_scenario"]

  #==============================================================================
  # CONTROL PANEL SERVICES
  #==============================================================================
  # Services for the control panel GUI

  control_panel:
    extends: x-gui-base
    build:
      args:
        - PACKAGE_NAMES=${CONTROL_PANEL_PACKAGES}
    image: control_panel:latest
    pull_policy: build
    container_name: control_panel
    command: ["ros2", "launch", "auna_control", "control_panel.launch.py"]

  control_panel_robot1:
    extends: control_panel
    container_name: control_panel_robot1
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "control_panel.launch.py",
        "robot_index:=1",
      ]
    profiles: ["sim_robot1", "physical_robot1", "sim_scenario"]

  control_panel_robot2:
    extends: control_panel
    container_name: control_panel_robot2
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "control_panel.launch.py",
        "robot_index:=2",
      ]
    profiles: ["sim_robot2", "physical_robot2", "sim_scenario"]

  control_panel_robot3:
    extends: control_panel
    container_name: control_panel_robot3
    command:
      [
        "ros2",
        "launch",
        "auna_control",
        "control_panel.launch.py",
        "robot_index:=3",
      ]
    profiles: ["sim_robot3", "physical_robot3", "sim_scenario"]

  #==============================================================================
  # LOCALIZATION SERVICES
  #==============================================================================
  # Services for localization and state estimation

  ekf_localization_sim:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${EKF_PACKAGES}
    image: ekf_localization:latest
    pull_policy: build
    container_name: ekf_localization
    command: ["ros2", "launch", "auna_ekf", "ekf_sim.launch.py"]

  ekf_localization_sim_robot1:
    extends: ekf_localization_sim
    container_name: ekf_localization_robot1
    command:
      ["ros2", "launch", "auna_ekf", "ekf_sim.launch.py", "robot_index:=1"]
    profiles: ["sim_robot1", "sim_scenario"]

  ekf_localization_sim_robot2:
    extends: ekf_localization_sim
    container_name: ekf_localization_robot2
    command:
      ["ros2", "launch", "auna_ekf", "ekf_sim.launch.py", "robot_index:=2"]
    profiles: ["sim_robot2", "sim_scenario"]

  ekf_localization_sim_robot3:
    extends: ekf_localization_sim
    container_name: ekf_localization_robot3
    command:
      ["ros2", "launch", "auna_ekf", "ekf_sim.launch.py", "robot_index:=3"]
    profiles: ["sim_robot3", "sim_scenario"]

  #==============================================================================
  # AUTONOMOUS DRIVING SERVICES
  #==============================================================================
  # Services for autonomous behavior algorithms

  # Wall following algorithm - basic autonomous driving behavior
  wallfollowing:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${WALLFOLLOWING_PACKAGES}
    image: wallfollowing:latest
    pull_policy: build
    container_name: wallfollowing
    command: ["ros2", "launch", "wallfollowing", "wallfollowing.launch.py"]
    profiles: ["wallfollowing"]

  #==============================================================================
  # DEVELOPMENT SERVICES
  #==============================================================================
  # Services for development and debugging

  # Development environment - interactive container for development
  development:
    extends: x-dev-base
    image: development:latest
    pull_policy: build
    container_name: development
    command:
      [
        "/bin/bash",
        "-c",
        "cd packages && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && /bin/bash",
      ]
    profiles: ["development"]

  talker:
    extends: x-package-base
    build:
      args:
        - INSTALL_PACKAGE_NAMES=${DEMO_PACKAGES}
    image: talker:latest
    pull_policy: build
    container_name: talker
    command: ["ros2", "run", "demo_nodes_cpp", "talker"]
    profiles: ["talker"]

  listener:
    extends: x-package-base
    build:
      args:
        - INSTALL_PACKAGE_NAMES=${DEMO_PACKAGES}
    image: listener:latest
    pull_policy: build
    container_name: listener
    command: ["ros2", "run", "demo_nodes_cpp", "listener"]
    profiles: ["listener"]

  tf2_trees:
    extends: x-package-base
    build:
      args:
        - PACKAGE_NAMES=${TF2_TOOLS_PACKAGES}
    image: tf2_trees:latest
    pull_policy: build
    container_name: tf2_trees
    volumes:
      - .:/home/ubuntu/workspace:cached
    command: [
        "bash",
        "-c",
        "ros2 run tf2_tools view_frames && \
        ros2 run tf2_tools view_frames --ros-args -r /tf:=/robot1/tf -r /tf_static:=/robot1/tf_static && \
        ros2 run tf2_tools view_frames --ros-args -r /tf:=/robot2/tf -r /tf_static:=/robot2/tf_static && \
        ros2 run tf2_tools view_frames --ros-args -r /tf:=/robot3/tf -r /tf_static:=/robot3/tf_static",
      ]
    profiles: ["tf2_trees"]
