include:
  - compose/docker-compose.base.yml
  - compose/docker-compose.simulation.yml
  - compose/docker-compose.robots.yml
  - compose/docker-compose.development.yml
  - compose/docker-compose.communication.yml
