vesc_driver_node:
  ros__parameters:
    port: "/dev/ttyACM0"
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 50.0
    current_min: 0.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 0.925
    servo_min: 0.125
    speed_max: 23250.0
    speed_min: -23250.0

vesc_to_odom_node:
  ros__parameters:
    odom_frame: "$(NAMESPACE_FRAME)$odom"
    base_frame: "$(NAMESPACE_FRAME)$base_link"
    speed_to_erpm_gain: -4614.0
    speed_to_erpm_offset: 0.0
    use_servo_cmd_to_calc_angular_velocity: True
    steering_angle_to_servo_gain: -1.0
    steering_angle_to_servo_offset: 0.525
    wheelbase: 0.32
    publish_tf: False

ackermann_to_vesc_node:
  ros__parameters:
    speed_to_erpm_gain: 4614.0
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: -1.0
    steering_angle_to_servo_offset: 0.525
