/**/ekf_filter_node:
    ros__parameters:
        frequency: 50.0

        sensor_timeout: 1.0

        two_d_mode: true

        print_diagnostics: true

        debug: false

        debug_out_file: ./file.txt

        permit_corrected_publication: false

        publish_acceleration: false

        publish_tf: true

        use_sim_time: false

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: odom
        odom0_config: [false,  false,  false,
                       false, false, true,
                       true, true, false,
                       false, false, false,
                       false, false, false]

        imu0: imu
        imu0_config: [false, false, false,
                      false, false,  true,
                      false, false, false,
                      false,  false,  false,
                      false,  false,  false]
        imu0_remove_gravitational_acceleration: true
        imu0_relative: true