# packages/src/auna_ekf/config/ekf/ekf_global.yaml
/**/ekf_global_node:
  ros__parameters:

    frequency: 20.0
    sensor_timeout: 0.5
    two_d_mode: true
    print_diagnostics: true
    transform_time: 0.0

    map_frame: map  # For this EKF, map_frame is odom
    odom_frame: odom     # Standard odom frame name
    base_link_frame: base_link # Standard base_link frame name
    world_frame: map    # This EKF operates in the odom world_frame

    publish_tf: true     # This EKF MUST publish the odom->base_link TF

    pose0: gazebo_pose
    pose0_config: [true, true, false, # X, Y, Z
                   false, false, true, # Roll, Pitch, Yaw
                   false,  false,  false, # dX, dY, dZ
                   false, false, false,  # dRoll, dPitch, dYaw
                   false, false, false] # ddX, ddY, ddZ
    pose0_differential: false
    pose0_relative: false # Velocities in odom message are usually not relative to filter's last state
    pose0_queue_size: 10

    process_noise_covariance: [
      1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.03,0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.03,0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.03,0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.06,0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.025, 0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.01,  0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.01,  0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.02,  0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.01,0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.015
    ]

    initial_estimate_covariance: [
      1.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    1.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    1.0e-9, 0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    1.0e-9, 0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    1.0e-9, 0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,  # Yaw (idx 5)
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      1.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      1.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      1.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      1.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.001,    0.0,    0.0,    0.0,  # vYaw (idx 11)
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      1.0e-9, 0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    1.0e-9, 0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    1.0e-9
    ]