# packages/src/auna_ekf/config/ekf/ekf_local.yaml
/**:
  ros__parameters:

    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    print_diagnostics: true

    map_frame: map      # For this EKF, map_frame is odom
    odom_frame: odom     # Standard odom frame name
    base_link_frame: base_link # Standard base_link frame name
    world_frame: odom    # This EKF operates in the odom world_frame

    publish_tf: true     # This EKF MUST publish the odom->base_link TF

    imu0: imu
    imu0_config: [false, false, false, # X, Y, Z
                  true,  true,  true,  # Roll, Pitch, Yaw
                  false, false, false, # dX, dY, dZ
                  true,  true,  true,  # dRoll, dPitch, dYaw
                  true,  true,  true] # ddX, ddY, ddZ
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: true

    odom0: odom
    odom0_config: [true, true, false, # X, Y, Z
                   false, false, false, # Roll, Pitch, Yaw
                   true,  true,  false, # dX, dY, dZ
                   false, false, true,  # dRoll, dPitch, dYaw
                   false, false, false] # ddX, ddY, ddZ
    odom0_differential: true
    odom0_relative: false # Velocities in odom message are usually not relative to filter's last state
    odom0_queue_size: 10

    # pose0 (GPS) is intentionally omitted for this EKF instance

    process_noise_covariance: [
      1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.03,0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.03,0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.03,0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.06,0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.025, 0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.01,  0.0,   0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.01,  0.0,   0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.02,  0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.01,0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0, 0.0, 0.015
    ]

    initial_estimate_covariance: [
      1.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    1.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    1.0e-9, 0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    1.0e-9, 0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    1.0e-9, 0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,  # Yaw (idx 5)
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      1.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      1.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      1.0,      0.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      1.0,      0.0,      0.0,    0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.001,    0.0,    0.0,    0.0,  # vYaw (idx 11)
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      1.0e-9, 0.0,    0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    1.0e-9, 0.0,
      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    1.0e-9
    ]