# /packages/src/auna_ekf/config/ekf/navsat.yaml
/**:
  ros__parameters:
    frequency: 10.0
    wait_for_datum: false
    gps0: gps/fix          # our simulated GPS (NavSatFix) from MoCap
    odom0: odometry/local_odom  # use local EKF odom->base as initial pose
    broadcast_utm_transform: false
    publish_filtered_gps: false