TARGET = sensor_parameter get_distance get_distance_intensity get_multiecho get_multiecho_intensity sync_time_stamp calculate_xy find_port

URG_LIB = ../src/liburg_c.a

include ../build_rule.mk

CFLAGS = -O2 $(INCLUDES) -I../include
LDLIBS = -lm $(shell if test `echo $(OS) | grep Windows`; then echo "-lwsock32 -lsetupapi"; fi)

all : $(TARGET)

clean :
	$(RM) *.o $(TARGET)

$(TARGET) : open_urg_sensor.o $(URG_LIB)

$(URG_LIB) :
	cd $(@D)/ && $(MAKE) $(@F)
